name: BuildImage.yml

on:
  push:
    branches:
      - master

jobs:
  checks:
    name: checkout
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  push_image:
    needs:
      - checks
    name: push_docker
    runs-on: ubuntu-22.04
    steps:
      - name: getDockerAndCode
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: log
        run: ls -la
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hardware-shop:latest
            ${{ secrets.DOCKER_USERNAME }}/hardware-shop:${{ github.sha }}

  push_aws:
    name: aws
    runs-on: ubuntu-22.04
    steps:
      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSHKEY}}
      - name: hello_world
        run: ls -la