name: BuildImage.yml

on:
  push:
    branches:
      - master

jobs:
  push_image:
    name: push_docker
    runs-on: ubuntu-22.04
    steps:
      - name: getDockerAndCode
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: log
        run: ls -la
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hardware-shop:latest
            ${{ secrets.DOCKER_USERNAME }}/hardware-shop:${{ github.sha }}

  push_aws:
    needs: push_image
    name: aws
    runs-on: ubuntu-22.04
    steps:
      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSHKEY }}

      - name: Deploy on EC2 (appleboy ssh)
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSHKEY }}
          port: 22
          script: |
            sudo docker ps -a
            sudo docker ps -q | xargs -r sudo docker stop
            sudo docker ps -aq | xargs -r sudo docker rm -v
            sudo docker images -q | xargs -r sudo docker rmi -f
            sudo docker run -d -p 80:8080 --name hardware-shop javierpalacios8080/hardware-shop:latest